### ISSUE TITLE
DataGrid - Data Properties & Grid Resize Bugs

### ISSUE THREAD

**Issue by csaper** [akorchev/radzen#14] opened 2016-11-10 20:28 UTC
- After dragging and dropping the DataGrid component onto the canvas, the event list panel does not display the "Properties" configuration fields.
- When attempting to resize the the DataGrid component, the handler appears to be ignoring the .mouseup() event when the mouse button is released.

Here is a video to provide a bit of visual context: 
[Radzen - DataGrid - Data Properties Not Displaying + Grid Resize Action Doesnt Respect Mouse Up.mp4.zip](https://github.com/akorchev/radzen/files/584368/Radzen.-.DataGrid.-.Data.Properties.Not.Displaying.Grid.Resize.Action.Doesnt.Respect.Mouse.Up.mp4.zip)

[Running Version 1.0.0-alpha.6 (1.0.0-alpha.6) of Radzen on OSX 10.12.1]

**Comment by akorchev** [comment] 2016-11-10 20:48
Does clicking the "grid" label select the grid? I guess there is a JS error causing both issues. Does restarting Radzen help? Or going to the __My Applications_ screen and back?

**Comment by csaper** [comment] 2016-11-10 21:05
@akorchev - tried all of the above with no luck (Radzen restart; My Applications and back; etc). I opened the dev console in case the output helps.

[Radzen - DataGrid - Test 2.mp4.zip](https://github.com/akorchev/radzen/files/584446/Radzen.-.DataGrid.-.Test.2.mp4.zip)

**Comment by akorchev** [comment] 2016-11-10 21:38
This helps! The JS error prevents everything else from working. I suspect your data source has something Radzen doesn't support yet. Could you please attach here the __meta__ directory of your app zipped? You can remove any sensitive data such as your service URL. Those files will help me fix that problem and get back to you with a fix.

**Comment by akorchev** [comment] 2016-11-14 17:07
For what is worth I have released a new version of Radzen. You could check if the error is still present.

**Comment by akorchev** [comment] 2017-03-31 12:49
I cannot reproduce in latest versions. Closing for now. Feel free to reopen.

**Closed by akorchev** 2017-03-31 12:49 UTC
