### ISSUE TITLE
Unexpected Error: ENOENT: no such file or directory...

### ISSUE THREAD

**Issue by PaulSPatterson** [akorchev/radzen#25] opened 2017-04-20 16:58 UTC
Receiving the following "Unexpected error" message when creating a new page...

Error: ENOENT: no such file or directory, open 'C:\Source Code Misc\NewApp001\meta\pages\home.json'

Seems the page does get created though. 

![2017-04-20 10_56_15-radzen](https://cloud.githubusercontent.com/assets/1970258/25242811/32e9ebae-25b8-11e7-9588-875155958570.png)

**Comment by akorchev** [comment] 2017-04-20 17:04
This is not a known issue. Does the page open normally after restarting Radzen? If not please zip the entire meta directory and attach it here. Everything else looks normal and is supposed to work.

**Comment by PaulSPatterson** [comment] 2017-04-20 18:51
Yes, the page seems to get created normally, and I didn't have to restart Radzen.

**Comment by akorchev** [comment] 2017-04-20 19:06
This is a very odd error indeed. I suspect it could be some timing issue but I cannot reproduce it. Please let me know if you find what may be causing it.

**Comment by PaulSPatterson** [comment] 2017-04-20 19:55
Here's a video that, I hope, will help. It appears that the issue occurs randomly. At one point, a different exception appears when I attempt to delete a page (shown towards the end of the video). Possibly some race conditions occurring? 

Link to Video: https://1drv.ms/v/s!AidZ6xUCz8BjzH0mZ7UOskwo8sXV

**Comment by akorchev** [comment] 2017-04-20 20:08
Thank you for recording a video! I will try following the exact same steps and will hopefully reproduce the error. I will post my findings tomorrow.

**Comment by akorchev** [comment] 2017-04-21 20:25
I think I fixed that in 1.0.2.

**Comment by akorchev** [comment] 2017-04-23 09:03
@PaulSPatterson did you have a chance to update to the latest version? Does the problem exist there?

**Comment by akorchev** [comment] 2017-05-05 13:49
@PaulSPatterson will close this. Feel free to reopen if you still experience this issue.

**Closed by akorchev** 2017-05-05 13:49 UTC

**Comment by ThomasSteschulat** [comment] 2018-03-19 22:10
I run into the same problem with the latest version. After i deleted some pages and remaned some pages. 
Some pages.. espacially these named "menu tile..." or menu stamm..." 
Here is a video about the problem: 
https://www.screencast.com/t/ElYxHNlG

**Comment by ThomasSteschulat** [comment] 2018-03-19 22:13
Here is my meta data folder. i hope its helpful.
[meta.zip](https://github.com/akorchev/radzen/files/1827139/meta.zip)

i cant build the app because of the error.

Kid Regards
Thomas

**Comment by ThomasSteschulat** [comment] 2018-03-19 22:13
If you need anything else let me know ;-)

**Comment by akorchev** [comment] 2018-03-20 05:50
Indeed a lot of pages are missing and I had to delete them manually from app.json in order to build the applicaton. There could be an issue with umlauts. Is there any chance to send us your DB schema as an SQL CREATE script? This will allow us to test. You can send it over to info@radzen.com

**Comment by ThomasSteschulat** [comment] 2018-03-20 07:50
I think so too. umlaute may cause the problem. in menu tiles has a foreign key to itsself. that may play a role?!
i send an email with the full database schema to info@radzen.com. 
the problem occurs after renaming a lot of pages, deleteing some and inferring and creating cruds's a few tables because i deleted too much pages.

Greets
Thomas
